name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
      GITHUB_SHA_SHORT=$(git rev-parse --short "$GITHUB_SHA")
      docker build . --file Dockerfile --tag pycolors:$GITHUB_SHA_SHORT
